# Generated by Django 2.1.2 on 2018-12-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='port',
            name='id',
        ),
        migrations.AddField(
            model_name='port',
            name='port_number',
            field=models.IntegerField(default=6901, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
