# Generated by Django 2.1.2 on 2018-12-12 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0005_image_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='serial_number',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
